"""
Memory Schemas.

Pydantic models for agent events:
- RelationshipSummary: Compact bilateral relationship for ~50 tokens per relation
- NotableEvent: World events for ~20 tokens each
- MyAction: Past actions for ~25 tokens each
"""

from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field


class EventType(str, Enum):
    """Types of notable events."""
    # Diplomatic events (world news)
    WAR_DECLARED = "WAR_DECLARED"
    PEACE_SIGNED = "PEACE_SIGNED"
    PEACE_REJECTED = "PEACE_REJECTED"
    ALLIANCE_FORMED = "ALLIANCE_FORMED"
    ALLIANCE_UPGRADED = "ALLIANCE_UPGRADED"
    ALLIANCE_DOWNGRADED = "ALLIANCE_DOWNGRADED"
    ALLIANCE_BROKEN = "ALLIANCE_BROKEN"
    ALLIANCE_REJECTED = "ALLIANCE_REJECTED"
    DIPLOMATIC_MESSAGE = "DIPLOMATIC_MESSAGE"
    REQUEST_PEACE = "REQUEST_PEACE"
    PROPOSE_ALLIANCE = "PROPOSE_ALLIANCE"
    
    # Military events (world news)
    ATTACK = "ATTACK"
    COMBAT_RESULT = "COMBAT_RESULT"
    TERRITORY_LOST = "TERRITORY_LOST"
    TERRITORY_GAINED = "TERRITORY_GAINED"
    NUCLEAR_STRIKE = "NUCLEAR_STRIKE"
    TROOPS_MOBILIZED = "TROOPS_MOBILIZED"  # Troops moved to border
    
    # Economic events (world news)
    TRADE_DEAL = "TRADE_DEAL"
    GENERAL_STRIKE = "GENERAL_STRIKE"
    
    # Internal crisis events (generated by engine, not actions)
    ECONOMIC_CRISIS = "ECONOMIC_CRISIS"
    CIVIL_UNREST = "CIVIL_UNREST"
    
    # Global Scenarios
    GLOBAL_SCENARIO = "GLOBAL_SCENARIO"

# Base Importance Scores for Salience Calculation
EVENT_IMPORTANCE = {
    # Tier S (100)
    EventType.WAR_DECLARED: 100,
    EventType.NUCLEAR_STRIKE: 100,
    EventType.CIVIL_UNREST: 100,
    EventType.ECONOMIC_CRISIS: 100,
    EventType.TERRITORY_LOST: 100,
    EventType.TERRITORY_GAINED: 100,
    EventType.GLOBAL_SCENARIO: 100,
    
    # Tier A (70)
    EventType.ALLIANCE_FORMED: 70,
    EventType.ALLIANCE_BROKEN: 70,
    EventType.ALLIANCE_UPGRADED: 70,
    EventType.PEACE_SIGNED: 70,
    
    # Tier B (40)
    EventType.TRADE_DEAL: 40,
    EventType.GENERAL_STRIKE: 40,
    EventType.TROOPS_MOBILIZED: 40,
    EventType.ATTACK: 40,
    EventType.COMBAT_RESULT: 40,
    
    # Tier C (20)
    EventType.DIPLOMATIC_MESSAGE: 20,
    EventType.REQUEST_PEACE: 20,
    EventType.PEACE_REJECTED: 20,
    EventType.PROPOSE_ALLIANCE: 20,
    EventType.ALLIANCE_REJECTED: 20,
    EventType.ALLIANCE_DOWNGRADED: 20,
}


class RelationshipSummary(BaseModel):
    """
    Compact summary of bilateral relationship.
    
    Pre-computed and updated after each turn.
    Target: ~30-50 tokens per relationship when rendered.
    """
    other_nation_id: str
    other_nation_name: str
    
    # Current state (from world state)
    relationship: str = "PEACE"  # WAR, PEACE, ALLIANCE
    trust: float = 50.0  # 0-100
    trust_trend: str = "→"  # ↑ rising, ↓ falling, → stable
    
    # Last interaction
    last_interaction_turn: Optional[int] = None
    last_interaction_summary: Optional[str] = None  # "They proposed alliance"
    
    # Notable events in this relationship (max 3, most recent)
    notable_events: List[str] = Field(default_factory=list)  # ["T5: broke treaty"]
    
    def to_prompt_line(self) -> str:
        """
        Render as compact prompt line (~30-50 tokens).
        
        Example:
        "Valdoria: WAR, Trust 15 (falling). Last: attacked us T24. History: T15: broke treaty"
        """
        parts = [f"{self.other_nation_name}: {self.relationship}, Trust {self.trust:.0f}"]
        
        # Trust trend
        if self.trust_trend == "↑":
            parts[0] += " (rising)"
        elif self.trust_trend == "↓":
            parts[0] += " (falling)"
        
        # Last interaction
        if self.last_interaction_turn is not None and self.last_interaction_summary:
            parts.append(f"Last: {self.last_interaction_summary} T{self.last_interaction_turn}")
        
        # Notable events (max 2 for brevity)
        if self.notable_events:
            history = "; ".join(self.notable_events[-2:])
            parts.append(f"History: {history}")
        
        return ". ".join(parts)


class NotableEvent(BaseModel):
    """
    Significant world event.
    
    Can be global or nation-specific.
    Target: ~20 tokens when rendered.
    """
    turn: int
    event_type: EventType
    actors: List[str] = Field(default_factory=list)  # Nation IDs involved
    summary: str  # "Valdoria attacked Aquilonia's northern border"
    relevance_to: Optional[List[str]] = None  # None = global, else specific nations
    
    def to_prompt_line(self) -> str:
        """
        Render as compact prompt line (~20 tokens).
        
        Example: "Turn 24: Valdoria attacked Aquilonia's northern border"
        """
        return f"Turn {self.turn}: {self.summary}"
    
    def is_critical(self) -> bool:
        """Check if this is a critical event (never pruned)."""
        critical_types = {
            EventType.WAR_DECLARED,
            EventType.PEACE_SIGNED,
            EventType.ALLIANCE_FORMED,
            EventType.ALLIANCE_BROKEN,
            EventType.NUCLEAR_STRIKE,
            EventType.TERRITORY_LOST,
            EventType.TERRITORY_GAINED,
            EventType.GLOBAL_SCENARIO,
        }
        return self.event_type in critical_types

    def calculate_salience(self, current_turn: int, evaluate_for_nation_id: Optional[str] = None) -> float:
        """
        Calculate the salience score of this event.
        Salience = Base Importance * (0.90 ^ Age) * Relevance Multiplier
        """
        # 1. Base Importance
        base_score = EVENT_IMPORTANCE.get(self.event_type, 10.0) # Default to 10 if missing
        
        # 2. Time Decay (10% decay per turn)
        age = max(0, current_turn - self.turn)
        time_factor = 0.90 ** age
        
        # 3. Relevance Multiplier
        relevance_mult = 1.0
        if evaluate_for_nation_id:
            # If they are a direct actor, boost importance by 50%
            if evaluate_for_nation_id in self.actors:
                relevance_mult = 1.5
            # If the event is specifically relevant to them (e.g., targeted crisis)
            elif self.relevance_to and evaluate_for_nation_id in self.relevance_to:
                relevance_mult = 1.5
                
        return base_score * time_factor * relevance_mult

class MyAction(BaseModel):
    """
    Past action taken by a nation (ego-centric).
    
    Each nation only sees their own actions.
    Target: ~25 tokens when rendered.
    """
    turn: int
    domain: str  # "Defense", "Economy", "Foreign"
    action_type: str  # "MOVE_TROOPS", "INVEST_WELFARE", "PROPOSE_ALLIANCE"
    action_summary: str  # "Moved 50 troops to Province 7"
    outcome: Optional[str] = None  # "SUCCESS", "FAILED", "ACCEPTED", "REJECTED"
    outcome_reason: Optional[str] = None # "Insufficient budget", "Trust too low", etc.
    reasoning: Optional[str] = None # Presidential or Ministerial reasoning
    
    def to_prompt_line(self) -> str:
        """
        Render as compact prompt line (~25 tokens).
        
        Example: "Turn 24 [Defense]: Attacked Valdoria's Province 7 → FAILED (Insufficient materials)"
        """
        line = f"Turn {self.turn} [{self.domain}]: {self.action_summary}"
        
        if self.outcome:
            line += f" → {self.outcome}"
            if self.outcome in ["FAILED", "REJECTED"] and self.outcome_reason:
                line += f" ({self.outcome_reason})"
        
        # Optionally include reasoning if for the President (Ministers don't see their own reasoning, but President does)
        if self.domain == "President" and self.reasoning:
            line += f" | Reasoning: {self.reasoning[:60]}..."
            
        return line

    def calculate_salience(self, current_turn: int) -> float:
        """
        Calculate the salience score of this action.
        Actions generally have lower base importance (25) but decay slower for continuity.
        """
        base_score = 25.0
        
        # Boost successful actions slightly (more salient for planning next steps)
        if self.outcome in ["SUCCESS", "ACCEPTED", "APPROVED"]:
            base_score = 35.0
            
        # Treat Presidential VETOs as highly salient (70) so they aren't quickly forgotten
        if self.domain == "President" and self.outcome == "VETOED":
            base_score = 70.0
        
        # Time Decay (10% decay per turn)
        age = max(0, current_turn - self.turn)
        time_factor = 0.90 ** age
        
        return base_score * time_factor
